apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e4bzmr70s-java-quarkus
  janus-idp.io/tekton: e4bzmr70s-java-quarkus
  backstage.io/kubernetes-id: e4bzmr70s-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e4bzmr70s-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
